// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                  = new(Query)
	LoginEvent         *loginEvent
	Organization       *organization
	Principal          *principal
	PrincipalAttribute *principalAttribute
	User               *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	LoginEvent = &Q.LoginEvent
	Organization = &Q.Organization
	Principal = &Q.Principal
	PrincipalAttribute = &Q.PrincipalAttribute
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                 db,
		LoginEvent:         newLoginEvent(db, opts...),
		Organization:       newOrganization(db, opts...),
		Principal:          newPrincipal(db, opts...),
		PrincipalAttribute: newPrincipalAttribute(db, opts...),
		User:               newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	LoginEvent         loginEvent
	Organization       organization
	Principal          principal
	PrincipalAttribute principalAttribute
	User               user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		LoginEvent:         q.LoginEvent.clone(db),
		Organization:       q.Organization.clone(db),
		Principal:          q.Principal.clone(db),
		PrincipalAttribute: q.PrincipalAttribute.clone(db),
		User:               q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		LoginEvent:         q.LoginEvent.replaceDB(db),
		Organization:       q.Organization.replaceDB(db),
		Principal:          q.Principal.replaceDB(db),
		PrincipalAttribute: q.PrincipalAttribute.replaceDB(db),
		User:               q.User.replaceDB(db),
	}
}

type queryCtx struct {
	LoginEvent         ILoginEventDo
	Organization       IOrganizationDo
	Principal          IPrincipalDo
	PrincipalAttribute IPrincipalAttributeDo
	User               IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		LoginEvent:         q.LoginEvent.WithContext(ctx),
		Organization:       q.Organization.WithContext(ctx),
		Principal:          q.Principal.WithContext(ctx),
		PrincipalAttribute: q.PrincipalAttribute.WithContext(ctx),
		User:               q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
