openapi: 3.0.0
servers:
  - url: 'http://localhost:8080'

info:
  version: <VERSION>
  title: Khoai NATS Admin API

components:
  securitySchemes:
    BearerToken:
      type: http
      scheme: bearer
    Roles:
      type: openIdConnect
      openIdConnectUrl: ""

paths:
  /v1/login/start:
    $ref: "./auth.yaml#/loginStart"
  /v1/login/exchange:
    $ref: "./auth.yaml#/loginExchange"